version: '3.8'
services:
  postgres:
    image: 'postgres:16.3'
    container_name: prontuario-postgres
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres"]
      interval: 2s
      timeout: 3s
      retries: 5  

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prontuario-api
    command: ["sh", "-c", "npx prisma migrate deploy && npm run build && npm run start:prod"]
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://api:3000/"]
      interval: 15s
      timeout: 3s
      retries: 5 
      start_period: 30s 

networks:
  app-network:
    driver: bridge