services:
  postgres-dev:
    image: 'postgres:16.3'
    container_name: prontario-dev-postgres
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5435:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
